---
- name: Remove existing cron job if exists
  cron:
    name: "{{ app_name }} artisan scheduler"
    state: absent

- name: Setup cronjob for artisan scheduler
  cron:
    name: "{{ app_name }} artisan scheduler"
    job: "php {{ app_path }}/artisan schedule:run 1>> /dev/null 2>&1"