---
- name: Run artisan migrate
  command: "php {{ app_path }}/artisan migrate"
  when: deploy_type != 'none'

- name: Run artisan db:seed
  command: "php {{ app_path }}/artisan db:seed"
  when: deploy_type == 'new'